### PR TITLE
completed user-can-create-entry.

### PR DESCRIPTION
**Pull request by david-s-song**
https://user-images.githubusercontent.com/90665895/161188875-664f7248-09ef-43c5-ae4e-fd4a9cbbcd96.mov

### CODE REVIEW

**Comment by david-s-song** [comment]
https://user-images.githubusercontent.com/90665895/161189311-be4c81f1-4aae-4cc6-b185-28db8085057c.mov

**Comment by david-s-song** [comment]
https://user-images.githubusercontent.com/90665895/161409490-ac7bc017-78dd-45e8-9382-ab09c79eb767.mov

**Comment by david-s-song** [comment]
https://user-images.githubusercontent.com/90665895/161667362-9393424a-b7ca-4ba2-ad64-9e4f54bc1df5.mov

**Review by Zhiwutian — APPROVED** [review]
👍🏼

**Pull request merged**
